Feofanova Mary
IKholopov/winapi2019 pull request #4
Opened 2019-02-21 04:41 UTC by mary3000

TODO:

- Comments

- Style

- More performance tests

- Commit/Decommit rework(?)

- Part 3: Canaries

2019-03-05 09:59 UTC, IKholopov requested changes

2019-03-05 09:59 UTC, IKholopov commented on .gitignore
> +!.gitignore
Добавь .vcxproj и .vcxproj.filters для быстрой сборки проекта

2019-03-05 09:59 UTC, IKholopov commented on FirstApp/BlockNode.cpp
> +#include "BlockNode.h"
Не вижу смысла в этом файле. Лучше написать CBlockNode() = default; и ~CBlockNode() = default; в хэдере

2019-03-05 09:59 UTC, IKholopov commented on FirstApp/BlockNode.h
> +	char * ptr;
char* (форматирование)

2019-03-05 09:59 UTC, IKholopov commented on FirstApp/CustomClass.cpp
> +#include "CustomClass.h"
Однострочные методы можно оставить в хэдере и обойтись без этого .cpp

2019-03-05 09:59 UTC, IKholopov commented on FirstApp/HeapManager.cpp
> +int main_() {
?

2019-03-13 15:52 UTC, mary3000 commented on .gitignore
> +!.gitignore
fixed

2019-03-13 15:52 UTC, mary3000 commented on FirstApp/BlockNode.cpp
> +#include "BlockNode.h"
fixed

2019-03-13 15:52 UTC, mary3000 commented on FirstApp/BlockNode.h
> +	char * ptr;
fixed

2019-03-13 15:53 UTC, mary3000 commented on FirstApp/CustomClass.cpp
> +#include "CustomClass.h"
fixed

2019-03-13 15:53 UTC, mary3000 commented on FirstApp/HeapManager.cpp
> +int main_() {
fixed

2019-03-13 21:07 UTC, IKholopov approved these changes

2019-03-13 21:08 UTC, IKholopov commented
Ok, но релизная версия компилируется в вечный цикл

2019-03-13 21:08 UTC, closed without merging