Haven't written tests yet
IKholopov/winapi2019 pull request #6
Opened 2019-02-21 08:58 UTC by lionsoon

2019-03-13 21:35 UTC, IKholopov requested changes

2019-03-13 21:35 UTC, IKholopov commented on HeapManager.cpp
> +	for (auto &i : allblocks) //.begin(); i != allblocks.end(); i = allblocks.erase(i))
Styleguide (скобки)

2019-03-13 21:35 UTC, IKholopov commented on HeapManager.cpp
> +	for (auto &i : allblocks) //.begin(); i != allblocks.end(); i = allblocks.erase(i))
И код в комментариях

2019-03-13 21:35 UTC, IKholopov commented on HeapManager.cpp
> +void * HeapManager::Alloc(size_t size) {
void(

2019-03-13 21:35 UTC, IKholopov commented on HeapManager.h
> +		std::cout << "> ";
Не надо привязываться к std::cout

2019-03-13 21:35 UTC, IKholopov commented on HeapManager.h
> +	struct block {
**B**lock

2019-03-13 21:35 UTC, IKholopov commented on Tester.cpp
> +	if (c.type == 0)
Скобки

2019-03-13 21:35 UTC, IKholopov commented on main.cpp
> +	int z; std::cin >> z;
Не надо так делать

2019-03-13 21:35 UTC, IKholopov commented on Tester.h
> +	void AddAllocator(void*(*alloc)(size_t), void(*free)(void*), std::string name);
Может будем std::function принимать? У нас вроде C++>=14, а не C99 :)

2019-03-18 17:12 UTC, lionsoon commented on HeapManager.cpp
> +	for (auto &i : allblocks) //.begin(); i != allblocks.end(); i = allblocks.erase(i))
fixed

2019-03-18 17:12 UTC, lionsoon commented on HeapManager.cpp
> +void * HeapManager::Alloc(size_t size) {
fixed

2019-03-18 17:12 UTC, lionsoon commented on HeapManager.h
> +		std::cout << "> ";
fixed

2019-03-18 17:12 UTC, lionsoon commented on HeapManager.h
> +	struct block {
fixed

2019-03-18 17:12 UTC, lionsoon commented on Tester.cpp
> +	if (c.type == 0)
fixed

2019-03-18 17:12 UTC, lionsoon commented on main.cpp
> +	int z; std::cin >> z;
fixed

2019-03-18 17:12 UTC, lionsoon commented on Tester.h
> +	void AddAllocator(void*(*alloc)(size_t), void(*free)(void*), std::string name);
fixed

2019-03-18 19:19 UTC, IKholopov approved these changes

2019-03-18 19:20 UTC, closed without merging